### ISSUE TITLE
fluffi_fluffiweb_1 container error

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#132]
Attached log(this is on refactor-and-deployment-and-doc branch):

![VirtualBox_ubuntu18 04_07_04_2020_12_33_16](https://user-images.githubusercontent.com/26308356/78653568-fefe6300-78cb-11ea-91cb-b29a678de55f.png)

*** Starting uWSGI 2.0.17 (64bit) on [Tue Apr  7 12:31:48 2020] ***
compiled with version: 6.4.0 on 27 March 2018 12:43:27
os: Linux-5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020
nodename: b6aec27acd92
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 3
current working directory: /app
detected binary path: /usr/sbin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.9 (default, Oct 17 2019, 12:14:22)  [GCC 6.4.0]
Python main interpreter initialized at 0x5624d2ab9f40
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1239640 bytes (1210 KB) for 16 cores
*** Operational MODE: preforking ***
2020-04-07 12:31:49,675 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "./main.py", line 12, in <module>
    from app import app
  File "./app/__init__.py", line 21, in <module>
    app.config.from_object("config")
  File "/usr/local/lib/python3.6/site-packages/flask/config.py", line 170, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/utils.py", line 546, in import_string
2020-04-07 12:31:54,332 INFO exited: uwsgi (exit status 22; not expected)
    __import__(import_name)
  File "./config.py", line 18, in <module>
    + "/fluffi_gm"
socket.gaierror: [Errno -3] Try again
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
2020-04-07 12:31:55,334 INFO spawned: 'uwsgi' with pid 74
[uWSGI] getting INI configuration from /app/uwsgi.ini
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini

;uWSGI instance configuration
[uwsgi]
cheaper = 2
processes = 16
ini = /app/uwsgi.ini
module = main
callable = app
wsgi-disable-file-wrapper = true
enable-threads = true
ini = /etc/uwsgi/uwsgi.ini
socket = /tmp/uwsgi.sock
chown-socket = nginx:nginx
chmod-socket = 664
hook-master-start = unix_signal:15 gracefully_kill_them_all
need-app = true
die-on-term = true
plugin = python3
show-config = true
;end of configuration

**Comment by jones718** [comment]
It seems like the connection to the database fails. Are you sure it is running and reachable with the user fluffi_gm, password fluffi_gm and hostname db.fluffi ?

**Comment by joyride9999** [comment]
Seems db its running ... also had to add in  hosts this line
10.66.0.1 	web.fluffi apt.fluffi mon.fluffi pole.fluffi gm.fluffi db.fluffi

![VirtualBox_ubuntu18 04_08_04_2020_18_20_21](https://user-images.githubusercontent.com/26308356/78801688-aad7a980-79c5-11ea-9578-ee874c997b7c.png)

**Comment by jones718** [comment]
Ok so probably the socket.gethostbyname('db.fluffi') fails. Maybe you can try to replace the function with your hostname hardcoded in server/fluffi/data/fluffiweb/config.py line 17.

**Comment by p4cx** [comment]
Only "[Errno -3]" is specified in the container log. The error message points to "[Errno -3] Temporary error in name resolution". I suspect the error is in your setup. What happens if you run the following command/code in the container where the web GUI is running?
```
python3
>>> import socket
>>> socket.gethostbyname('db.fluffi')
```
If this fails, you should check whether db.fluffi is fully accessible. If not, please let us know so that we can conduct further investigations.

**Comment by joyride9999** [comment]
Running on the container i got this :
```
docker exec -ti fluffi_fluffiweb_1 "python3"
Python 3.6.8 (default, Jan 30 2019, 23:54:38) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostbyname('db.fluffi')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -3] Try again
>>> import os
>>> os.system("ping -c 3 db.fluffi")
ping: bad address 'db.fluffi'
256
>>> os.system("ping -c 3 10.66.0.1")
PING 10.66.0.1 (10.66.0.1): 56 data bytes
64 bytes from 10.66.0.1: seq=0 ttl=64 time=0.056 ms
64 bytes from 10.66.0.1: seq=1 ttl=64 time=0.053 ms
64 bytes from 10.66.0.1: seq=2 ttl=64 time=0.086 ms

--- 10.66.0.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.053/0.065/0.086 ms
0

```
So i replaced in config.py all references to scoekt.gethostbyname('db.fluffi') to 10.66.0.1.
(ps. if it is a requirement to have the ip 10.66.0.1 ... I don't see a reason to use socket.gethostbyname  anyway)
Also as on ubuntu18.04 desktop i could not make it work with networkd as per description, so i reverted back to networkmanager, and the network config file looks like this :
/etc/netplan/01-network-manager-all.yaml:
```
# Let networkd manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp0s3:
      dhcp4: yes
    enp0s8:
      dhcp4: no
      dhcp6: no
      addresses: [10.66.0.1/23]
      nameservers:
        search: [fluffi]
        addresses: [10.66.0.1] 
```

In the end got this error :


```
Cannot get systems from database or PoleMarch. (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '10.66.0.1' (timed out)")
(Background on this error at: http://sqlalche.me/e/e3q8)
Polemarch ist Mist
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 958, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 704, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1005, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '10.66.0.1' (timed out)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 41, in wrapper
    if not app.SYSTEMS_LOADED and len(models.Locations.query.all()) is 0:
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3178, in all
    return list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2239, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 704, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 1005, in connect
    raise exc
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '10.66.0.1' (timed out)"
```

**Comment by TomSie** [comment]
Replacing dns names with 10.66.0.1 will work if you run all server containers on the same machine. If, however, you distribute the containers accross multiple machines for load balancing, this will cause various bugs.

**Comment by TomSie** [comment]
In general it looks as if you are having troubles with the network setup. @p0wer0xff : I think the documentation to set up the FLUFFI network is not yet complete. For example: /etc/systemd/network/fluffi.network and /etc/systemd/network/default.network are created but never used. @p0wer0xff : Could you please have a look?

**Comment by joyride9999** [comment]
I've recreated the VM and reinstalled all from scratch. Indeed looks like something was miss configured on the previous machine.
