### ISSUE TITLE
http://web.fluffi:8880/systems returns 502

### ISSUE THREAD

**Issue by maverickwoo** [siemens/fluffi#96]
We believe we currently have a Fluffi master VM and two Linux Fluffi runner VMs that are running "as correctly as we know how to". The most important evidence in support of this belief includes:
1. The three periodic tasks in PoleMarch all run correctly: Polemarch has seen 0 error/interrupted/delay/offline events.
2. The two runner VMs can connect to the rest of the infra just fine: DNS queries, smbclient, etc. all work.

However, http://web.fluffi:8880/ actually shows http://web.fluffi:8880/static/images/load.png on the right half of the page. And if we visit http://web.fluffi:8880/systems, we get a 502 Bad Gateway and the container log is shown at the end of this message. Any idea what we should check next?

```
fluffiweb_1  | Traceback (most recent call last):
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
fluffiweb_1  |     return self.wsgi_app(environ, start_response)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
fluffiweb_1  |     response = self.handle_exception(e)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
fluffiweb_1  |     reraise(exc_type, exc_value, tb)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
fluffiweb_1  |     raise value
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
fluffiweb_1  |     response = self.full_dispatch_request()
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
fluffiweb_1  |     rv = self.handle_user_exception(e)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
fluffiweb_1  |     reraise(exc_type, exc_value, tb)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
fluffiweb_1  |     raise value
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
fluffiweb_1  |     rv = self.dispatch_request()
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
fluffiweb_1  |     return self.view_functions[rule.endpoint](**req.view_args)
fluffiweb_1  |   File "./app/views.py", line 1066, in systems
fluffiweb_1  |     changeAgentStarterModeForm=changeAgentStarterModeForm)
fluffiweb_1  |   File "./app/helpers.py", line 26, in renderTemplate
fluffiweb_1  |     return _renderTemplate(*args, nav = nav.elems, **kwargs)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
fluffiweb_1  |     context, ctx.app)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
fluffiweb_1  |     rv = template.render(context)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
fluffiweb_1  |     return original_render(self, *args, **kwargs)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
fluffiweb_1  |     return self.environment.handle_exception(exc_info, True)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
fluffiweb_1  |     reraise(exc_type, exc_value, tb)
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
fluffiweb_1  |     raise value.with_traceback(tb)
fluffiweb_1  |   File "/app/app/templates/systems.html", line 13, in top-level template code
fluffiweb_1  |     {% extends "base.html" %}
fluffiweb_1  |   File "/app/app/templates/base.html", line 50, in top-level template code
fluffiweb_1  |     {{ message }}
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
fluffiweb_1  |     {% block doc -%}
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
fluffiweb_1  |     {%- block html %}
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
fluffiweb_1  |     {% block body -%}
fluffiweb_1  |   File "/usr/local/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
fluffiweb_1  |     {% block content -%}
fluffiweb_1  |   File "/app/app/templates/systems.html", line 221, in block "content"
fluffiweb_1  |     {{ host.InstanceCount }} {% if host.confLM > 0 %} <div class="systems-lm-text">({{host.confLM}} LM)</div> {% endif %}
fluffiweb_1  | jinja2.exceptions.UndefinedError: 'app.utils.ansible. object' has no attribute 'confLM'
fluffiweb_1  | 2020/02/26 19:18:41 [error] 12#12: *89 upstream prematurely closed connection while reading response header from upstream, client: 10.180.62.146, server: , request: "GET /systems HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock:", host: "web.fluffi:8880", referrer: "http://web.fluffi:8880/index"
fluffiweb_1  | 10.180.62.146 - - [26/Feb/2020:19:18:41 -0500] "GET /systems HTTP/1.1" 502 173 "http://web.fluffi:8880/index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0" "-"
fluffiweb_1  | [pid: 16|app: 0|req: 13/56] 10.180.62.146 () {46 vars in 824 bytes} [Wed Feb 26 19:18:40 2020] GET /systems => generated 0 bytes in 478 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

**Comment by p4cx** [comment]
> However, http://web.fluffi:8880/ actually shows http://web.fluffi:8880/static/images/load.png on the right half of the page.

This only happens when no fuzzjob is currently running. When you start a fuzzjob, it should be in the table on the left and Grafana is embedded on the right with graphs (e.g. System CPU Utilization or Unique Crashes and Violations) for the fuzzjob.
